<?php include_once('header.php'); ?>
<?php include_once('nav-inner.php'); ?>
<article>
	<div class="container">
<h1>Privacy Terms</h1>
<p>At SYNERGYSOFT, WE RESPECT AND PROTECT THE PRIVACY OF VISITORS TO OUR WEBSITE, WWW.legendrepricing.com (THE &ldquo;SITE&rdquo;), AND OUR CUSTOMERS WHO USE OUR REPRICING PLATFORM, TOOLS AND SERVICES OFFERED ON THE SITE (THE &ldquo;SERVICE&rdquo;). SYNERGYSOFT KNOWS THAT YOU CARE ABOUT HOW YOUR INFORMATION IS USED AND SHARED. WE WANT TO MAKE SURE THAT YOU UNDERSTAND THE TYPE OF INFORMATION WE COLLECT ABOUT YOU, HOW IT IS USED AND THE SAFEGUARDS WE USE TO PROTECT IT. THIS PRIVACY POLICY (&ldquo;POLICY&rdquo;) EXPLAINS HOW WE COLLECT AND USE VISITORS&rsquo; AND CUSTOMERS&rsquo; INFORMATION AS PART OF OUR SITE AND OUR SERVICE.</p>
<p><strong>Last revision: January 19, 2015</strong></p>
<hr />
<p><strong>1. INFORMATION YOU PROVIDE</strong><br />In this Policy, &ldquo;personal information&rdquo; is data that can be used to uniquely identify or contact a single person, such as the individual&rsquo;s name, postal address, email address and telephone number. When You register for the Service, We ask for information such as your name, company name and address, site name, phone number, e-mail address and credit card information. If You sign-up for the free trial account, You are not required to enter your credit card information until You decide to continue with a paid plan. SYNERGYSOFT uses a third-party intermediary to manage credit card processing. This intermediary is not permitted to store, retain, or use your billing information, except for the sole purpose of credit card processing on SYNERGYSOFT&rsquo;s behalf.</p>
<p><strong>2. INFORMATION WE COLLECT</strong><br />As is true with most web sites, SYNERGYSOFT gathers certain information automatically and stores it in log files. This information includes internet protocol addresses as well as browser, internet service provider, referring/exit pages, operating system, date/time stamp, and click stream data. Occasionally We may connect personal information to data gathered in our log files, as necessary to improve the Service to individual customers. Otherwise We mostly use this information with no connection to individual users, to analyze trends, administer the Site, or track usage of various features within the Site.</p>
<p><strong>3. COOKIES</strong><br />A &ldquo;cookie&rdquo; is a piece of information either stored temporarily (session cookie) or placed on your computer&rsquo;s hard drive (persistent cookie). The main purpose of a cookie is to allow a web server to identify a user, and serve up customized web pages and/or login information to the user&rsquo;s web browser when revisiting a web page. Cookies help us promptly display the information You need and other information which We consider to be of interest to You. By gathering and remembering information about your website preferences through cookies We can provide a better web and marketing experience.</p>
<p>When You visit the Site or use the Service, We use &ldquo;session cookies&rdquo; to allow the Site or Service to uniquely identify your browser while You are logged in and to enable SYNERGYSOFT to process your online transactions. Session cookies also help us confirm your identity and are required in order to use the Service. We also use &ldquo;persistent cookies&rdquo; that only We can read and use, to identify You as a SYNERGYSOFT customer and make it easier for You to log into the Service.</p>
<p>As a user You can accept or decline the use of cookies through a functionality built into most web browsers. Users who disable their web browsers&rsquo; ability to accept cookies will be able to browse our Site, but will not be able to access or take advantage of the Service.</p>
<p><strong>4. CLEAR GIFS</strong><br />Our third-party tracking utility company employs a software technology called clear gifs that helps us better manage content on our site by informing us what content is effective. Clear gifs are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of Web users. Unlike cookies, which are stored on a user&rsquo;s computer hard drive, clear gifs are embedded invisibly on Web pages.</p>
<p>We tie the information gathered by clear gifs to our customers&rsquo; personal information, and use them in our HTML-based emails to learn which emails have been opened by recipients. This allows us to gauge the effectiveness of certain communications and our marketing campaigns. If You would like to opt-out of these emails, please follow the unsubscribe instructions within our marketing emails.</p>
<p><strong>5. HOW WE USE THE INFORMATION WE COLLECT</strong><br />SYNERGYSOFT may use the personal information and other information We collect about your use of the Service:</p>
<p>a) To operate the Service and tailor it to your needs<br />b) For billing, identification and authentication<br />c) To contact You about Your use of the Service<br />d) To send you marketing materials<br />e) For research purposes<br />f) To generally improve the content and functionality of the Service and the Site.</p>
<p>Although SYNERGYSOFT owns all rights to the software, code, databases, and other Service applications, You retain all rights to your data.</p>
<p><strong>6. HOW THIRD PARTIES USE THE INFORMATION WE COLLECT</strong><br />SYNERGYSOFT may also share your personal information with its third-party vendors (such as its credit card processor) and hosting partners to provide the necessary hardware, software, networking, storage, and other services We use to operate the Service and maintain quality user experience. Our service providers will be permitted to obtain only the personal information they need to deliver the service. They are required to maintain the confidentiality of the information and are prohibited from using it for any other purpose than for delivering the service to SYNERGYSOFT in accordance with SIVAM SA&rsquo;s instructions and policies.</p>
<p>Except as described in this Policy, SYNERGYSOFT will not give, sell, rent or loan any personal information to any third party. We may disclose such information to respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims. We may also share such information if we believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of our Terms of Service, or as otherwise required by law. SYNERGYSOFT may also provide non-personal, summary or group statistics about our customers, sales, traffic patterns, and related Site information to reputable third-party vendors, but these statistics will include no personal information.</p>
<p><strong>7. LINKS TO OTHER SITES</strong><br />Our Site contains links to other websites that are not owned or controlled by SYNERGYSOFT. Please be aware that We do not determine and We are not responsible for the privacy practices or content of such other sites. We encourage You to be aware when you leave our Site, and read the privacy statements of other websites linked to our Site. This Policy applies only to information collected by this Site.</p>
<p><strong>8. PUBLIC FORUMS</strong><br />Our Site offers publicly-accessible blogs or community forums. You should be aware that any information You provide in these areas may be read, collected, and used by others who access them. To request removal of your personal information from our blog or community forum, contact us at admin<a href="mailto:admin@legendrepricing.com">@legendrepricing.com</a>. In some cases, We may not be able to remove your personal information, in which case We will let You know if We are unable to do so and why.</p>
<p><strong>9. CUSTOMER TESTIMONIALS/COMMENTS/REVIEWS</strong><br />From time to time, We post customer testimonials on the Site which may contain personal information. We do obtain the customers&rsquo; consent to post their names along with their testimonials.</p>
<p><strong>10. PROTECTION OF INFORMATION</strong><br />SYNERGYSOFT is committed to ensuring the security of your personal information. We take every precaution to protect the confidentiality and security of the personal information placed on the Site or used within the Service, by employing technological, physical and administrative security safeguards, such as firewalls and carefully-developed security procedures. For example, when You enter sensitive information (such as login credentials and all your activity on our Service platform) We encrypt the transmission of that information using secure socket layer technology (SSL). These technologies, procedures and other measures help ensure that your data is safe, secure, and only available to You and to those You authorized access.</p>
<p><strong>11. OPTING-OUT</strong><br />We process and store information on behalf of our customers. If You are our customer and would like to opt-out of getting communications from SYNERGYSOFT please contact us at admin<a href="mailto:admin@legendrepricing.com">@legendrepricing.com</a> or follow the unsubscribe instructions included in each marketing email. Requests to opt-out of transfers to our third-party vendors will also be considered, but limitations on data sharing may make it difficult or impossible to provide the Service.</p>
<p><strong>12. DATA RETENTION</strong><br />SYNERGYSOFT will retain personal information We process on behalf of our customers for as long as needed to provide Service to our customers, subject to our compliance with this Policy. We retain and use this personal information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>
<p><strong>13. CHILDREN</strong><br />SYNERGYSOFT does not knowingly collect any personal information from children under the age of 13. If we learn that we have collected the personal information of a child under 13 we will take steps to delete the information.</p>
<p><strong>14. BUSINESS TRANSACTIONS</strong><br />SYNERGYSOFT may assign or transfer this Policy, and your user account and related information and data, to any person or entity that acquires or is merged with SYNERGYSOFT.</p>
<p><strong>15. CHANGES TO THE PRIVACY POLICY</strong><br />If We make any material changes to this Policy We will notify You by email or by posting a prominent notice on the Site prior to the change becoming effective. We encourage You to periodically review this page for the latest information on our privacy practices. Your continued use of the Site or Service constitutes your agreement to be bound by such changes to this Policy. <strong>Your only remedy, if You do not accept the terms of this Policy, is to discontinue use of the Site and Service.</strong></p>
<p><strong>16. TERMS OF SERVICE</strong><br />When You access and use the Service, You are subject to the SYNERGYSOFT Terms of Service, found here: <a href="https://legendrepricing.com/home/tos">https://legendrepricing.com/home/tos</a>.</p>
<p><strong>17. CONTACT US</strong><br />If You have questions regarding this Policy or about the privacy practices of SYNERGYSOFT, please contact us by email at admin@<a href="mailto:admin@legendrepricing.com">legendrepricing.com</a></p>
	</div>
</article>
<?php include_once('footer.php'); ?>
