<?php include_once('header.php'); ?>
<?php include_once('nav-inner.php'); ?>
<article>
	<div class="container">
			<h1>Refund Policy</h1>
<p><strong><strong>REFUNDS, </strong>CANCELLATION AND TERMINATION, </strong><strong>BILLING, PLAN MODIFICATIONS</strong><br />Billing and Payments. The Service is made available on a pay-as-you-go basis and is charged at the start of Your elected subscription term (generally monthly or annually). If You do not provide Your credit card or other payment information to SYNERGYSOFT before the expiration of any free trial period, Your account will be suspended until payment information and charge authorization are provided. You will be promptly billed and, if applicable, any trial period will terminate. Thereafter, Your subscription will renew automatically based on Your plan&rsquo;s renewal cycle. The Service provides an interface for the account owner to change credit card information (e.g., upon card renewal). The account owner will receive a receipt upon each payment received, or they may obtain a receipt from within the application to be able to track the status of Your subscription.</p>
<p>Modifying Your Subscription. If You choose to upgrade Your plan during Your elected subscription period, any incremental cost will be prorated over the remaining term of the subscription period and charged to Your account. Subsequently, You will be charged the adjusted rate on Your next billing cycle. If You are on a monthly billing cycle, You will not see a prorated charge or credit in the current month, but Your new billing rate will be reflected on Your next monthly bill. Regardless of Your billing cycle, <strong>there are no refunds or credits for partial months of Service, plan downgrades, or refunds for unused time.</strong> No exceptions will be made. Downgrading Your plan level may cause the loss of content, features, or capacity of Your account and SYNERGYSOFT does not accept any liability for such loss. If your monthly usage exceeds your selected plan allowance, or significantly exceeds the average monthly usage (as determined solely by SIVAM SA), we reserve the right to immediately upgrade, disable or throttle your account.</p>
<p>Overdue Charges. If You fail to pay your subscription fee on time, or if Your credit card payment information is entered in error or does not go through for processing and You do not update payment information upon Our request, your entire subscription may be suspended or cancelled.</p>
<p>Billing Privacy. SYNERGYSOFT uses a third-party intermediary to manage credit card processing and this intermediary is not permitted to store, retain, or use Your billing information except to process Your credit card information for SIVAM SA. For more information about Our billing practices and Your personal information please visit Our Privacy Policy: <a href="https://www.legendrepricing.com/privacy-policy" target="_blank">https://www.legendrepricing.<wbr />com/privacy-policy</a>.</p>
<p>Taxes. Unless otherwise stated, Our charges do not include any taxes, levies, duties or similar governmental assessments, including value-added, sales, use or withholding taxes assessable by any local, state, provincial or foreign jurisdiction (collectively &ldquo;Taxes&rdquo;). You are responsible for paying Taxes except those assessable against SYNERGYSOFT based on its income. We will invoice You for such Taxes if we believe we have a legal obligation to do so.</p>
<p>Price Changes. SYNERGYSOFT reserves the right to change prices without prior notification as long as current accounts remain at the rates that were active at the time of subscription. Changes to the rates affecting existing accounts will be made only after timely notification has been sent. Such notifications will be posted on the SIVAM SA Site (<a href="http://legendrepricing.com/" target="_blank">legendrepricing.com</a>) and sent via email to the email address each customer has provided during registration.</p>
<p><strong>CANCELLATION AND TERMINATION</strong><br />You are responsible for canceling Your account, and can cancel Your account by clicking on the account link located in the menu at the top of the screen. There are no other means of canceling Your account. Once You cancel Your account You will lose access to all of Your content, and We preserve the right to delete all such content in the normal course of operation. This content cannot be recovered once Your account is cancelled. If You cancel the Service before the end of Your current paid-up subscription period, Your cancellation will take effect immediately and You will not be charged again.</p>
<p>SYNERGYSOFT reserves the right to (i) modify or discontinue, temporarily or permanently, the Service (or any part thereof) and (ii) refuse any/all current and future use of the Service, suspend or terminate your account or any part thereof (or Your use of the Service), and remove and discard any of Your content within the Service if We believe that You have violated these Terms. SIVAM SA will use all reasonable efforts to contact You directly via email to warn You prior to suspension or termination of Your account. Any suspected fraudulent, abusive, or illegal activity may be grounds for immediate termination of Your use of Service, and may be referred to law enforcement authorities. SIVAM SA shall not be liable to You or any third party for any modification, suspension or discontinuation of the Servic</p>
	</div>
</article>
<?php include_once('footer.php'); ?>
